### ISSUE TITLE
Can you help me make it work please

### ISSUE THREAD

**Issue by Zied-mess** [yoannchb-pro/MoodleGPT#23]
I tried to configure it, but it doesn't work. Also, could you please tell me how to activate the code? Should I just type it randomly in the navigator?
 When I refresh the gptmodel it says : undefined can you help me please ?

**Comment by Zied-mess** [comment]
![screenshot](https://github.com/yoannchb-pro/MoodleGPT/assets/14153145/f48e759e-d905-4627-b71e-e8e17bcb046f)

**Comment by yoannchb-pro** [comment]
Hello, for the ChatGPT version you can look into the OpenAI website to find one because the button is not working anymore. And for the code you can type everything you want and then enter it on the keyboard after focusing the noodle quiz to inject the code. You can look at other many closed issues of the same kind to solve it.

**Comment by Zied-mess** [comment]
thank you so much now I have this issue I searched for the closed issue but I didn't find this :
![Uploading issue.png…]()

**Comment by Zied-mess** [comment]
Je peux avoir ton discord s'il vous plait pour avoir une petite call pour tu m'aide à le fonctionner ?

**Comment by yoannchb-pro** [comment]
Je te l’enverrais quand je serais de retour. Je suis en vacances actuellement.
