### ISSUE TITLE
GPT model isnt loading

### ISSUE THREAD

**Issue by arieldavenport** [yoannchb-pro/MoodleGPT#32]
<img width="651" alt="image" src="https://github.com/yoannchb-pro/MoodleGPT/assets/8864075/9f488582-1a21-4f7e-a4b5-2e0417756ba9">

This is what shows up in the log.

**Comment by arieldavenport** [comment]
<img width="264" alt="image" src="https://github.com/yoannchb-pro/MoodleGPT/assets/8864075/b5a6088c-533b-4392-b084-bd1d40aa462b">

**Comment by yoannchb-pro** [comment]
Hello, you currently have a 404 error because the gpt model is not correct. I'm currently fixing this bug in the new version but the button to get the last model isn't working for now. If you want something working you can download the version on the dev branch (https://github.com/yoannchb-pro/MoodleGPT/tree/dev) otherwise enter manually the model by checking here https://platform.openai.com/docs/models/gpt-3-5-turbo.

**Comment by arieldavenport** [comment]
Thank you!

—
Ariel Davenport
979-549-5010
________________________________
