### ISSUE TITLE
Error message - TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by sherrykidtht** [yoannchb-pro/MoodleGPT#4]
<img width="666" alt="Screen Shot 2023-06-15 at 11 39 59" src="https://github.com/yoannchb-pro/MoodleGPT/assets/136697989/1c6723b0-6a02-4cbb-bc72-f50ae019ee8b">

Hi, Could you help me with it. It doesn't work on my browser. I've tried Arc and Chrome.

**Comment by yoannchb-pro** [comment]
Hello, Can you please open the console (F12 -> console) and show me the content of it when you try to complete a question ?
I you get a 429 error it because your tokens expired or may be you used all of them. The only solution is too enter a billing adresse in openai, set a limit per month and to create a new api key (don't wory it's like 0.01$ every 100 request).

**Comment by sherrykidtht** [comment]
Hi, it looks like that
<img width="552" alt="Screen Shot 2023-06-15 at 15 20 41" src="https://github.com/yoannchb-pro/MoodleGPT/assets/136697989/739f7086-0f1e-4e5a-b1ed-5cff575ab2ee">

**Comment by yoannchb-pro** [comment]
Yhea you got same error as me. The tokens are only available for free during 3 month. Just need to enter a billing dress, create new api key, set a limit (for example 1$ per month) and it should be fix.

**Comment by sherrykidtht** [comment]
Many thanks, it works! I can find the answer in the console, but it cannot select the radio button automatically for me. 

<img width="1644" alt="Screen Shot 2023-06-15 at 16 04 36" src="https://github.com/yoannchb-pro/MoodleGPT/assets/136697989/fc0d529f-93cd-4f83-be15-725bd08825d0">

**Comment by yoannchb-pro** [comment]
Are you in autocomplete mode and do you have mousehover effect activated ?
